### ISSUE TITLE
使用该项目遇到俩个问题。

### ISSUE THREAD

**Issue by YuQi9797** [Ucoon/flutter_app_template#1]
作者您好，我想采用您的模板，但目前存在一些问题：https://github.com/Ucoon/flutter_app_template/blob/a0458bfc509599e3b00bc8d4ec1e4e258d6d276d/lib/widget/layout/src/tab/bottom_tab_bar_view.dart#L27
The class 'PreferredSizeWidget' can't be used as a mixin because it's neither a mixin class nor a mixin. (Documentation)

以及
https://github.com/Ucoon/flutter_app_template/blob/main/lib/widget/flow_animation_widget.dart#L7
Missing concrete implementation of 'RenderObjectElement.moveRenderObjectChild'. (Documentation)

请问该如何解决呢？

**Comment by Ucoon** [comment]
已升级flutter版本至3.24.0，更新下最新代码
